name: Build & Deploy Cloud Run Job (Vertex Pipeline)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      PROJECT_ID: ${{ secrets.GOOGLE_PROJECT }}
      REGION: us-central1
      IMAGE_NAME: vertex_pipeline


    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup gcloud
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ secrets.GOOGLE_PROJECT }}
        service_account_key: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
        install_components: 'gke-gcloud-auth-plugin'
        export_default_credentials: true

    # Construir y publicar la imagen Docker en Artifact Registry
    - name: build and push the docker image 
      env:
        GOOGLE_PROJECT: ${{ secrets.GOOGLE_PROJECT }} 
      run: | 
        # Configurar Docker para autenticar con Artifact Registry
        gcloud auth configure-docker us-central1-docker.pkg.dev
        # Construir imagen
        docker build -t us-central1-docker.pkg.dev/$GOOGLE_PROJECT/images/$IMAGE_NAME:latest ./despliegue_cloud_run
        # Publicar imagen Docker en Artifact Registry
        docker push us-central1-docker.pkg.dev/$GOOGLE_PROJECT/images/$IMAGE_NAME:latest


    - name: Deploy Cloud Run Job
      run: |
        gcloud run jobs deploy run-pipeline-job \
          --image us-central1-docker.pkg.dev/$GOOGLE_PROJECT/images/$IMAGE_NAME \
          --region $REGION \
          --service-account cloud-run-sa@${PROJECT_ID}.iam.gserviceaccount.com \
          --set-env-vars PROJECT_ID=${PROJECT_ID},\
          LOCATION=us-central1,\
          PIPELINE_PATH=gs://mlops13/projectB/pipeline-prediction/pipeline_bigquery.json,\
          SERVICE_ACCOUNT=vertex-process@mlops13.iam.gserviceaccount.com,\
          VALIDA_TABLE=mlops13.github_mlops.census_by_age,\
          INPUT_AGE=60 \
          --quiet
